{% set name = "mycotools" %}
{% set version = "0.30.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 08f47a0150a19bf98b5be6dfccf3c80b16efe00481d06915842f80281d5f8272

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - openpyxl
    - pip
    - python ==3.9.15
    - requests
  run:
    - biopython ==1.79
    - openpyxl ==3.0.10
    - pandas ==1.2.4
    - python ==3.9.15
    - requests ==2.28.1
    - scipy ==1.6.3
    - ete3 ==3.1.2
    - pip
    - diamond
    - blast
    - iqtree ==2.2.0.3
    - fasttree ==2.1.10
    - mafft
    - mmseqs2
    - hmmer ==3.3.2
    - tqdm

test:
  imports:
    - mycotools
    - mycotools.lib
    - mycotools.utils

about:
  home: "https://github.com/xonq/mycotools/mycotools"
  license: "BSD 3-Clause"
  license_family: BSD
  license_file: "/users/PAS1046/osu10393/scripts/mycotools/LICENSE"
  summary: "Bleeding-edge comparative genomics automation and standardization software"
  doc_url: "https://github.com/xonq/mycotools"
  dev_url: "https://github.com/xonq/mycotools"

extra:
  recipe-maintainers:
    - xonq
